FROM nginx:1.29-alpine

# Nginx will serve static files from here
WORKDIR /usr/share/nginx/html

# Remove default config
RUN rm -f /etc/nginx/conf.d/default.conf

# Copy nginx config
COPY nginx.ecs.conf /etc/nginx/nginx.conf

# Copy frontend into nginx html folder
COPY frontend/ /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
