FROM nginx:1.29-alpine

# remove default site config (optional)
RUN rm -f /etc/nginx/conf.d/default.conf

# copy our nginx config
COPY nginx.ecs.conf /etc/nginx/nginx.conf

#  copy frontend into nginx html folder
COPY frontend/ /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
